import LinkedList from './linkedList'

const linkedList = new LinkedList<number>()
linkedList.push(10)
linkedList.push(20)
linkedList.push(30)
// console.log(linkedList.removeAt(3))
// console.log(linkedList.removeAt(2))
// console.log(linkedList.getElementAt(3))
// console.log(linkedList.getElementAt(2))
// console.log(linkedList.indexOf(10))
// console.log(linkedList.indexOf(20))
// console.log(linkedList.indexOf(30))
// console.log(linkedList.indexOf(40))
// console.log(linkedList.remove(10))
// console.log(linkedList.remove(20))
// console.log(linkedList.remove(30))
// console.log(linkedList.remove(40))
console.log(linkedList.insert(40, 4))
console.log(linkedList.insert(1, 0))
console.log(linkedList.insert(3, 1))
console.log(linkedList.insert(2, 4))
console.log(linkedList.size())
console.log(linkedList.toString())
console.log(linkedList)

